# 왜 안될까용?
# 이게 왜 안되지?
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(SUM(B.REVIEW_SCORE)/COUNT(*),2)
FROM REST_INFO A
JOIN REST_REVIEW B
ON A.REST_ID = B.REST_ID
GROUP BY A.REST_ID
HAVING A.ADDRESS LIKE '서울%'
ORDER BY AVG(B.REVIEW_SCORE) DESC, A.FAVORITES DESC


# SELECT A.REST_ID, B.REST_NAME, B.FOOD_TYPE, B.FAVORITES, B.ADDRESS, ROUND(AVG(A.REVIEW_SCORE),2) AS SCORE
# FROM REST_REVIEW A
# JOIN REST_INFO B ON A.REST_ID = B.REST_ID
# GROUP BY A.REST_ID
# HAVING B.ADDRESS LIKE '서울%'
# ORDER BY SCORE DESC, B.FAVORITES DESC