SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
where status = 'DONE'
group by a.writer_id
having sum(price) >= 700000
ORDER BY sum(price)


# SELECT B.USER_ID, B.NICKNAME, SUM(PRICE) AS TOTAL_SALES
# FROM USED_GOODS_BOARD AS A JOIN USED_GOODS_USER AS B ON A.WRITER_ID = B.USER_ID
# WHERE STATUS = 'DONE'
# GROUP BY A.WRITER_ID
# HAVING TOTAL_SALES >= 700000
# ORDER BY TOTAL_SALES